{% set version = '0.3.3.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppeigen
  version: {{ version|replace("-", "_") }}

source:
  fn: RcppEigen_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RcppEigen_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppEigen/RcppEigen_{{ version }}.tar.gz
  sha256: 11020c567b299b1eac95e8a4d57abf0315931286907823dc7b66c44d0dd6dad4

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: inline, RUnit, pkgKitten
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-matrix >=1.1_0
    - r-rcpp >=0.11.0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix >=1.1_0
    - r-rcpp >=0.11.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RcppEigen')"           # [not win]
    - "\"%R%\" -e \"library('RcppEigen')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://dirk.eddelbuettel.com/code/rcpp.eigen.html
  license: GPL (>= 2) | file LICENSE
  summary: 'R and ''Eigen'' integration using ''Rcpp''. ''Eigen'' is a C++ template library for
    linear algebra: matrices, vectors, numerical solvers and related algorithms.  It
    supports dense and sparse matrices on integer, floating point and complex numbers,
    decompositions of such matrices, and solutions of linear systems. Its performance
    on many algorithms is comparable with some of the best implementations based on
    ''Lapack'' and level-3 ''BLAS''. The ''RcppEigen'' package includes the header files
    from the ''Eigen'' C++ template library (currently version 3.3.4). Thus users do
    not need to install ''Eigen'' itself in order to use ''RcppEigen''. Since version
    3.1.1, ''Eigen'' is licensed under the Mozilla Public License (version 2); earlier
    version were licensed under the GNU LGPL version 3 or later. ''RcppEigen'' (the
    ''Rcpp'' bindings/bridge to ''Eigen'') is licensed under the GNU GPL version 2 or
    later, as is the rest of ''Rcpp''.'

  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RcppEigen
# Type: Package
# Title: 'Rcpp' Integration for the 'Eigen' Templated Linear Algebra Library
# Version: 0.3.3.4.0
# Date: 2018-02-05
# Author: Douglas Bates, Dirk Eddelbuettel, Romain Francois, and Yixuan Qiu; the authors of Eigen for the included version of Eigen
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Copyright: See the file COPYRIGHTS for various Eigen copyright details
# Description: R and 'Eigen' integration using 'Rcpp'. 'Eigen' is a C++ template library for linear algebra: matrices, vectors, numerical solvers and related algorithms.  It supports dense and sparse matrices on integer, floating point and complex numbers, decompositions of such matrices, and solutions of linear systems. Its performance on many algorithms is comparable with some of the best implementations based on 'Lapack' and level-3 'BLAS'. The 'RcppEigen' package includes the header files from the 'Eigen' C++ template library (currently version 3.3.4). Thus users do not need to install 'Eigen' itself in order to use 'RcppEigen'. Since version 3.1.1, 'Eigen' is licensed under the Mozilla Public License (version 2); earlier version were licensed under the GNU LGPL version 3 or later. 'RcppEigen' (the 'Rcpp' bindings/bridge to 'Eigen') is licensed under the GNU GPL version 2 or later, as is the rest of 'Rcpp'.
# License: GPL (>= 2) | file LICENSE
# Depends: R (>= 2.15.1)
# LazyLoad: yes
# LinkingTo: Rcpp
# Imports: Matrix (>= 1.1-0), Rcpp (>= 0.11.0), stats, utils
# Suggests: inline, RUnit, pkgKitten
# URL: http://dirk.eddelbuettel.com/code/rcpp.eigen.html
# BugReports: https://github.com/RcppCore/RcppEigen/issues
# NeedsCompilation: yes
# Packaged: 2018-02-06 03:28:54.209006 UTC; edd
# Repository: CRAN
# Date/Publication: 2018-02-07 16:27:35 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
