travis:
  secure:
    BINSTAR_TOKEN: I119CCV8+lJQckepJIJtkmCgCsY2y+7T+1VRgUpqhOIrq3IPFK1uPsBdxCvp92sFQcjIPHRj38ymM4YgShTnzAc2pkh1A9aS81Rv+Djee+Da0aHaEcTmOro80o/Pn0wE3bNpUPJBpZPklvxa5g3+KVOKfNIZt2CtppBp3Au0KUndrukWE3CNf/AIUsbd5BKTIX1tUJXqYhRJJZlLpTLxKUbJYkJ3OEp54rlT1nEUAuy9JdpF0d70BW5a2w+NoZhTVWg53jMCruYzz+wc6J9PdXt+ZFTA4YF15D9nlDfuKjSYuYFvGKYLOpJu6k8fTv0DFvhMMES9al7sdfWyLISV1sYybS2tRkS2VN3KKm7vTeQRGoM87mYW/QaHcanSZXtGo2kJsr/Vyh8NX0ixK3hrKWNw7iSQWC+6xorsEFvRr1enTkul07psLSNMHe9/lRttAz2BjcFRFpCta19hSneKbumARFbegBj95w4giyFfZHNKj229uxPGpjUmqCl8GkA0gnzxaNMjBKSTErx2hCcQ0V23k7YWcSa6H0JY5WyBxDevET6Y2cR8KTO4BIcox8YXPoum+ucI/lfU2ijVTzrLrDZmF6q8l/05IFwlrDmJoyngOVB/qRkR+KUBmI3VGyDV9sd0S4Tz+Z8RywG/VOFqRe2efW/Df45x1O59uRJKPNw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
