travis:
  secure:
    BINSTAR_TOKEN: tAt08RecrFU+UC77dhxiNEwVn2fDnzm3XQFs4bc7RE30w/6+aJbGKly/rBMWOxH4e8tYGtFdXqptgyVeKePdCwDLnNsHvpmZzlNuoaxqQdSTZhUZ8bb2OD5PbnfSicc2L9ueWTSIG1mVn9jglnMLUMWvc/EEsNUTlTaMlQnpdKPzuFcM0qMvPVqKSQw2qnJhXDt04qNogQV5YE0banORdptwQFogHdAifnpqCMsCqz3sp6MsJqZXmFBMtZ5GtggurUR0ETyC7xkTsGkgpCQHoU2oGR7ZhNAleErESgJ1IFXMI03S5hBjuPz4yC8i4Atzx08hL1k8zYS6zVi2JY7Hzj+ZjKbOGkgI4ZcILf6emeRXZxWVDaZ0tXblOBBrpXuHlwPc4C19Xn3srbTfaPIVCv9qLKr3/z6RU+DbKl/eEX58LlCtf3nAW/vmaGLq8o7Y+/4xQO+xrWF25twzV60QiGQHn9yHKuZ940HUxqCQmkO1684GO0NnsZY9WU/V+f8y9wK+SP30Yppy/H2lKfv3ZLL/cDJgRlPyNrD8frXQw/JpxnZTBM0WDppbgYBwr2CefoOh/xCQXarymHIc7UFOBy7/L6O7MQm9urAtc7zWP3S6uMHK6glzlXxyCwpavaU86UHuAASE+pYoKa4X/fPep7uDNO1fIOxC51jlqnFeftk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
