travis:
  secure:
    BINSTAR_TOKEN: GSgJdTR9kJxouReDACjhu1waplysz41vq1SMbb1fIO7Nk4l3PNeDfHddGP44gYv+XCgmLHXI+pFNLpYbAi1oJ7Zln9Atj6RaCKWnKCsPV7cmCWsvukU1OMmY+fAnyRp4hyMitrRsyzLvaxU6gGZ0dMAl6xkpYh7kYjSAiONLWyIqlkNCBLhD7mzdYz+JJTm3ZgD+o4yMfbxVEsN7S24TVuoaEXySuxmEcKalGOCNxdBBr3BTCVEJQIsBlUZ8QzJmUanyzO6OkBzfc1jaRbGQJD2+MunWCcJtnBFW63uUZ9GH4hRf2MySsLvkMdcz5cZiRnin2pQUa1WysIJd9xMUmjiupkvKzXIe3GT2l8PYXW1A0bSQGTnLXQGctZ4G0GbgBJ1t6c8YxgZCHgH6m4BPRuea0TOq4yAhYixpTeJMZKi5GshUdgW/IkZoZ/tqCGwcAF9fzAs67GPlW5pj76fBUCQ6rnYyYxvZZI7mNw104fvcsfgSMfIwp7L4uhdB6anA1YC//66vP7SGUYCVhD6urfRjb0RSEA/TGuxuXvXOor+qSG2HA7f6yc3S6HUas5dL8Jqir0eyvAtAXjyx8ROJt0SPADCZP2f9+PClWmzqp7MJkTuyV047X+uLhgtzEo9EPCdoZgumgzyz+ZR3lKiNXQzN78CCUG0XPAeKNPsXwPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
