travis:
  secure:
    BINSTAR_TOKEN: jTnqNZaoFbz97VzW58UmtAujvFPd5LozGfH9IDzMpMVt33fC3dr0b3KIMRj1OFulnbdMbXOPenXBQ1mS9bahxFuVmfnFiEqH0CgTHhWmRSWOpdPo2jICjT8OuesIu8vZlmQvST6aUoCqZnzwpoX+OEOfqloq5jjg4xrZFQgkXpUmtzbWcwe8zDZ3h6gIfBUuLVjjbXKCwvYghnHDvWvDw6ehdy2r5zcu9eGEX+5T0pPXWy1NHPdWoTNXabHMhmyT1OGR9axHUBg1uy7+I8hkEVeAO2APGYv/d7EK14wEUcaf8PVOSuojOz73CSwtKGxz+4A474Y/RDF/yyjdUTX3duuA/lusw7uInVLYqPKZd60abVDYLbUFDfchPcrTa5X4xY/t+T3D8Op4JSMivAVo8Xn1hqrPg3JsLQBizRXRCdY8zo/coKs6JzDffIqdXAhg/XQ/L5Xv/YiIpC0w63sYq6mOawCSCeBuW0nZXxZyqXuaqspR2lg+TZUtoLgFmtS8YyyzLmdUXXjJlPnW5pJZopfh5YvUIUGkWEM0hw63peBHwqDRq6yTurQlLIf+0RvMUnDROZrYlUP0+xuh6HoAMk/zEsL+7UBB5IJivVs8+YNDVDTy3fJ3wIxV84qiVV60udZHRVYegI/Ru9NFkgKuyi7O5yJlXynw/DbRw48+UhM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
