travis:
  secure:
    BINSTAR_TOKEN: gO5pP6ygiQoC887BeOYPkSDibYeWSY7ICzYthweBufvsCWyw8Taqv6CBWh63m3eu9GkYZ2sEa51Vs1dI2yelMo+SPtLY4yGB26rvTLX/YpOtNpfDv7v8MFKKZ4dJBZMjblcyT66XW34JfMcx/uFD69IWnmRM6vIfz14PA2fMvib7put3Fhk/R+40Vg30QQi0tVIqW/pYTzw1tC6oQybsHyCfQdtWb8pSLc+DsmTCJvZDB0qMf+2c64y7dxjdjY+PmYvcIerJn5oH/h88jCulBfm/xpobWCceCQgEJ+d67rOe0rM8qBRhOZxc1RoRZg0SZbLMDJhAs1z/UHKO74XWCgIP9nu3BIH0gBbZewYql6F01zgJ40ANu+E1IB3TN+Sej0h33QxJAVJD9BqwbOqGOQt55AEXW95tQg28Y48+hxjpNIxep8gTKQJqSWiP3oBycINXZMQH9rLlKWTt/SkehJVnbep+JwmRvfBDkx2Uh5A482r7MbY7mmpMxkazIvfpoDZljkF4BPcxSiik6q1QYo7vqCa+MfExT0qi6O3tLm68lLpZGrga1w6Hp64gzV9DN8mPu9oJtDTweizaBm29776yoDV+FCQxqdCkFwcDiKjR9UTJRdICw9+H3nYcuQmCf7Tbo840Qug/aZGS3vuV2fY3bn0IotNSYnRDb8FfQeI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
